Recover location info from MLIR after Water roundtrip
Uses the JSON format of diagnostics to reconstruct the stack trace and
point it back to Python source.

The error message resembles the following

```
RuntimeError: error: assertion known to be false
At /home/azinenko/git/wave/tests/kernel/wave/location_exception.py:28
26 |         tkw.read(a)
27 |
28*|     location = StackTraceInfo.capture_current_location()
29 |     with Context():
30 |         location_str = str(location.to_mlir())
31 |
called from /home/azinenko/git/wave/.venv/lib/python3.10/site-packages/_pytest/python.py:193
called from ...
called from ...
called from ...
```

A mechanism to override MLIR given to Water is added for testing
purposes.

Co-authored-by: Tim Gymnich <tim@gymni.ch>

Signed-off-by: Alex Zinenko <git@ozinenko.com>
Signed-off-by: Tim Gymnich <tim@gymni.ch>